@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor PKB_COLOR
skinparam classBackgroundColor PKB_COLOR

Package "Program Knowledge Base" <<Rectangle>>{
Interface PKBUpdateHandler <<Interface>>
Interface PKBQueryHandler <<Interface>>

Class PKB
Class PkbEntityTable
Class PkbPatternTable
Class PkbRelationshipTable

}

Class HiddenOutside #FFFFFF
HiddenOutside ..> PKB

PKB .left.|> PKBQueryHandler
PKB .right.|> PKBUpdateHandler
PKB -down-> "1..*" PkbEntityTable
PKB -down-> "1" PkbPatternTable
PKB -down-> "1..*" PkbRelationshipTable

@enduml
