@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor PKB_COLOR
skinparam classBackgroundColor PKB_COLOR

Package "Program Knowledge Base" <<Rectangle>>{
    
Interface PKBUpdateHandler <<Interface>> {
    + addRelationships(vector<Relationship>)
    + addEntities(vector<Entity>)
    + addPatterns(vector<Pattern>)
    + addCfgs(vector<CFGNode>)
}

Interface PKBQueryHandler <<Interface>> { 
    + retrieveAllStatementEntities() : vector<PQLEntity>
    + retrieveAllVariables() : vector<PQLEntity>
    + retrieveAllConstants() : vector<PQLEntity>
    + retrieveAllProcedureEntities() : vector<PQLEntity>
    + retrieveProcedureEntityByName(string) : PQLEntity
    + retrieveStatementByLineNumberAndType(int, StatementType) : PQLEntity
    + retrieveStatementEntitiesByType(StatementType) : vector<PQLEntity>
    + retrieveVariableByName(string): PQLEntity
    + retrieveConstantByValue(int) : PQLEntity
    + retrieveRelationshipsByTypeLhsAndRhs(RelationshipType, 
        ClauseArg, ClauseArg) : vector<PQLRelationship>
    + retrieveRelationshipsByType(RelationshipType) : vector<PQLRelationship>
    + retrievePatterns(StatementType, ClauseArg, ClauseArg) : vector<PQLPattern>
}

Class PKB 
Class PkbEntityTable
Class PkbPatternTable

Class PkbRelationshipTable {
    + addToRelationshipTable()  
}

Class PkbGraphManager

Class PkbRepository {
    
    + getCfgManager() : cfgManager
}

Class PkbQueryManager  {
    + retrieveRelationshipsByType(RelationshipType) : vector<PQLRelationship>
    + retrieveRelationshipByTypeAndLhsRhs(RelationshipType,
     ClauseArg, ClauseArg, PkbRepository): vector<PQLRelationship>
} 

Class PkbEntityQueryHelper
Class PkbPatternQueryHelper
Class PkbRelationshipQueryHelper

Class PkbGraphExtractor

Class PkbUpdateManager {
    + addRelationships(vector<Relationship>)
}
}
Class HiddenOutside #FFFFFF
HiddenOutside ..> PKB

PKB .left.|> PKBQueryHandler
PKB .right.|> PKBUpdateHandler
PKB -down--> "1" PkbQueryManager
PKB -down--> "1" PkbRepository
PKB -down-> "1" PkbUpdateManager

PkbUpdateManager -left-> PkbRepository

PkbRepository -down-> "1..*" PkbEntityTable
PkbRepository -down-> "1..*" PkbPatternTable
PkbRepository -down-> "1..*" PkbRelationshipTable
PkbRepository -down-> "1" PkbGraphManager

PkbQueryManager -down-> "1" PkbEntityQueryHelper
PkbQueryManager -down-> "1" PkbPatternQueryHelper
PkbQueryManager -down-> "1" PkbRelationshipQueryHelper

PkbRelationshipQueryHelper --> "*" PkbGraphExtractor

@enduml
