@startuml
!include style.puml

title
Querying Next*(s1, s2) in detail
end title

participant QPS as QPS QPS_COLOR

box "Problem Knowledge Base" PKB_COLOR_T1
participant ":PKB" as PKB PKB_COLOR
participant ":PkbQueryManager" as QueryManager PKB_COLOR
participant ":PkbRelationshipQueryHelper" as QueryHelper PKB_COLOR
participant "repo:PkbRepository" as Repo PKB_COLOR
participant ":PkbGraphNextStarRelationshipExtractor" as GraphExtractor PKB_COLOR
end box

QPS -> PKB: retrieveRelationshipsByTypeAndLhsRhs(type, lhs, rhs)
activate PKB

PKB -> QueryManager: retrieveRelationshipByTypeAndLhsRhs(type, lhs, rhs, repo)
activate QueryManager

QueryManager -> QueryManager: pkbTrackedRelationshipTypeToInternalType(type)
activate QueryManager

QueryManager --> QueryManager: PkbRelationshipType pkbType
deactivate QueryManager

QueryManager -> QueryHelper: retrieveRelationshipsFromGraphsByTypeAndLhsRhs(pkbType, lhs, rhs, repo)
activate QueryHelper

QueryHelper -> QueryHelper: retrieveNextStarByTypeAndLhsRhs(lhs, rhs, repo)
activate QueryHelper

QueryHelper -> Repo: getCfgs()
activate Repo

Repo --> QueryHelper: vector<CFGManager> cfgs
deactivate Repo

QueryHelper -> GraphExtractor: extractAllFromStart(startNode)
activate GraphExtractor

GraphExtractor --> QueryHelper: vector<PkbRelationship> relationships
deactivate GraphExtractor

QueryHelper --> QueryHelper: vector<PkbRelationship> relationships
deactivate QueryHelper

QueryHelper --> QueryManager: vector<PkbRelationship> relationships
deactivate QueryHelper

QueryManager --> PKB: vector<PQLRelationship> relationships
deactivate QueryManager

PKB --> QPS: vector<PQLRelationship> relationships
deactivate PKB

@enduml