@startuml
!include style.puml

title
Adding and querying relationships in detail
end title

actor User as User

box "Problem Knowledge Base" PKB_COLOR_T1
participant ":PKB" as PKB PKB_COLOR
participant ":PkbQueryManager" as QueryManager PKB_COLOR
participant ":PkbUpdateManager" as UpdateManager PKB_COLOR
participant ":PkbRepository" as Repo PKB_COLOR
end box

User -> PKB: addRelationships(vector<Relationship>)
activate PKB

PKB -> UpdateManager: addRelationships(vector<Relationship>)
activate UpdateManager

loop "relationships.size()"
    UpdateManager -> Repo: addToRelationshipTable()
    activate Repo

    Repo --> UpdateManager
    deactivate Repo   
end

UpdateManager --> PKB
    deactivate UpdateManager

PKB --> User
deactivate PKB

User -> PKB: retrieveRelationshipsByType(type)
activate PKB

PKB -> QueryManager: retrieveRelationshipsByType(type)
activate QueryManager

QueryManager -> Repo: getCfgManager()
activate Repo

Repo --> QueryManager: cfgManager
deactivate Repo

QueryManager -> QueryManager: internal handler methods
activate QueryManager

QueryManager --> QueryManager
deactivate QueryManager

QueryManager --> PKB: vector<PQLRelationship> relationships
deactivate QueryManager

PKB --> User: vector<PQLRelationship> relationships
deactivate PKB

@enduml