@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor QPS_COLOR
skinparam classBackgroundColor QPS_COLOR

Package "Query Processing System" <<Rectangle>>{

Class QPS
Class QPSTokenizer
Class QueryParser
Class QueryEvaluator
Class QueryResultsProjector
Class Query
Class SelectClause
Class RelationshipClause
Class PatternClause 
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> QPS

QPS .left.> QPSTokenizer : creates >
QPS ..> QueryParser : creates >
QPSTokenizer .down.> QueryParser: tokens >
QueryParser ..> Query: creates >
QueryEvaluator .down.> Query: executes >
Query -down-> "1" SelectClause
Query -down-> "0..*" RelationshipClause
Query -down-> "0..*" PatternClause
QPS .right.> QueryResultsProjector: creates >
QueryEvaluator .right.> QueryResultsProjector: results >
QPS .down.> QueryEvaluator: creates >

@enduml
