@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor SP_COLOR
skinparam classBackgroundColor SP_COLOR

Package "Source Processor" <<Rectangle>>{
Interface Extractor <<Interface>>

Class SourceProcessor
Class Lexer
Class ParserManager
Class EntityExtractor
Class PatternExtractor
Class "Extractor<Relationship>"
Class DesignExtractorManager
Class AST
}

Package PKB {
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> SourceProcessor

SourceProcessor .left.> Lexer: creates >
SourceProcessor ..> ParserManager: creates >
SourceProcessor *--> "1" DesignExtractorManager
SourceProcessor o-down-> "1" AST

DesignExtractorManager o--> "1" EntityExtractor
DesignExtractorManager o--> "1" PatternExtractor
DesignExtractorManager o--> "1..*" "Extractor<Relationship>"

EntityExtractor ..|> Extractor
PatternExtractor ..|> Extractor
"Extractor<Relationship>" ..|> Extractor

Lexer ..> ParserManager: tokens >

ParserManager .right.> AST: creates >
DesignExtractorManager .right.> PKB: stores >
@enduml
