@startuml
!include style.puml


actor User as User

box "Source Processor" SP_COLOR_T1
participant ":SourceProcessor" as SourceProcessor SP_COLOR
participant ":Lexer" as Lexer SP_COLOR
participant ":ParserManager" as ParserManager SP_COLOR
participant ":DesignExtractorManager" as DesignManager SP_COLOR
end box

box "Problem Knowledge Base" PKB_COLOR_T1
participant ":PKB" as PKB PKB_COLOR
end box

create SourceProcessor
User -> SourceProcessor: stream
activate SourceProcessor

create DesignManager
SourceProcessor -> DesignManager
activate DesignManager

DesignManager --> SourceProcessor
deactivate DesignManager

create Lexer
SourceProcessor -> Lexer
activate Lexer

SourceProcessor -> Lexer: tokenize(stream)
Lexer --> SourceProcessor: tokens
deactivate Lexer

create ParserManager
SourceProcessor -> ParserManager: tokens
activate ParserManager

SourceProcessor -> ParserManager: parse()

ParserManager --> SourceProcessor: AST
deactivate ParserManager

SourceProcessor --> User
deactivate SourceProcessor

User -> SourceProcessor: extractRelations()
activate SourceProcessor

SourceProcessor -> DesignManager: extractRelationships()
activate DesignManager

DesignManager --> SourceProcessor: relationships
deactivate DesignManager

SourceProcessor --> User: relationships
deactivate SourceProcessor

User -> PKB: addRelationships(relationships)

@enduml