@startuml
!include style.puml

title
Tokenization in detail
end title

box "Source Processor" SP_COLOR_T1
participant ":SourceProcessor" as SP SP_COLOR
participant ":Lexer" as Lexer SP_COLOR
end box

SP -> Lexer: tokenize(stream)
Lexer --> SP: vector<Tokens> tokens

@enduml