#include <common/FileIOManager.cpp>

#include <pkb/ProgramKnowledgeBase.cpp>
#include <pkb/interfaces/PKBQueryHandler.cpp>
#include <pkb/pkb_object/PKB.cpp>
#include <pkb/table_managers/EntityPkbTableManager.cpp>
#include <pkb/table_managers/ModifiesPkbTableManager.cpp>

#include <qps/QPS.cpp>
#include <qps/query/Query.cpp>
#include <qps/query/clause/ClauseArgument.cpp>
#include <qps/query/clause/EntityClauseResult.cpp>
#include <qps/query/clause/ModifiesPClause.cpp>
#include <qps/query/clause/ModifiesSClause.cpp>
#include <qps/query/clause/PQLEntity.cpp>
#include <qps/query/clause/PQLRelationship.cpp>
#include <qps/query/clause/RelationshipClauseResult.cpp>
#include <qps/query/clause/SelectClause.cpp>
#include <qps/query_evaluator/QueryEvaluator.cpp>
#include <qps/query_parser/DesignEntity.cpp>
#include <qps/query_parser/QueryParser.cpp>
#include <qps/query_parser/parsers/ClauseParser.cpp>
#include <qps/query_parser/parsers/DeclarationParser.cpp>
#include <qps/query_parser/parsers/ModifiesParser.cpp>
#include <qps/query_parser/parsers/SelectParser.cpp>
#include <qps/query_parser/parsers/SuchThatClauseParser.cpp>
#include <qps/query_tokenizer/QPSTokenizer.cpp>

#include <sp/SourceProcessor.cpp>
#include <sp/dataclasses/AST.cpp>
#include <sp/dataclasses/tokens/Token.cpp>
#include <sp/design_extractor/DesignExtractorManager.cpp>
#include <sp/design_extractor/EntityExtractor.cpp>
#include <sp/design_extractor/ModifiesExtractor.cpp>
#include <sp/design_extractor/PatternExtractor.cpp>
#include <sp/lexer/Lexer.cpp>
#include <sp/parser/SimpleSyntaxParserManager.cpp>
#include <sp/parser/rules/AssignSimpleSyntaxRule.cpp>
#include <sp/parser/rules/ConstantValueSimpleSyntaxRule.cpp>
#include <sp/parser/rules/NameSimpleSyntaxRule.cpp>
#include <sp/parser/rules/ProcedureSimpleSyntaxRule.cpp>
#include <sp/parser/rules/ProgramSimpleSyntaxRule.cpp>
#include <sp/parser/rules/ReadSimpleSyntaxRule.cpp>
#include <sp/parser/rules/SimpleSyntaxRule.cpp>
#include <sp/parser/rules/StatementListSimpleSyntaxRule.cpp>