name: CI for Cmake Project - Windows

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
    BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 30
    strategy:
      fail-fast: true

    steps:
      - uses: actions/checkout@v2
      - name: Unit & integration tests
        shell: bash
        run: |
          cd Team05/Code05
          mkdir build
          cd build
          cmake -A Win32 ..
          cmake --build . --target unit_testing --config Release
          cmake --build . --target integration_testing --config Release
          cd ../..
