name: CI for Cmake Project (Tests) - Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
    BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 30
    strategy:
      fail-fast: true

    steps:
      - uses: actions/checkout@v2
      - name: Build Unit & integration tests
        shell: bash
        run: |
          cd Team05/Code05
          mkdir build
          cd build
          cmake -A Win32 ..
          cmake --build . --target unit_testing --config Release
          cmake --build . --target integration_testing --config Release
          cd ../..
      - name: Run Unit & Integration tests
        shell: bash
        run: |
          Team05/Code05/build/src/unit_testing/Release/unit_testing.exe
          Team05/Code05/build/src/integration_testing/Release/integration_testing.exe